import pandas as pd
import numpy as np

class FactorEngineer:
    def __init__(self, config):
        self.target_horizon = config.TARGET_HORIZON_DAYS
        self.vol_window = config.VOLATILITY_WINDOW

    def build_factors(self, df):
        # df has MultiIndex (Date, Ticker) and columns [Close, Volume]
        # We need to unstack to calculate rolling features per ticker smoothly
        close_px = df['Close'].unstack(level=1)
        volume_px = df['Volume'].unstack(level=1)
        high_px = df['High'].unstack(level=1)
        low_px = df['Low'].unstack(level=1)
        
        daily_returns = close_px.pct_change(fill_method=None)
        
        # 1. Target: Forward returns (Shifted backwards to align with today's features)
        # Prevent Look-Ahead Bias: If TARGET_HORIZON is 5, today's target is Close_{t+5} / Close_t - 1
        forward_returns = close_px.shift(-self.target_horizon) / close_px - 1.0
        
        # 2. Risk/Volatility Factor: 20-day standard deviation of daily returns
        vol_20d = daily_returns.rolling(window=self.vol_window).std()
        
        # 3. Momentum Factors
        mom_1m = close_px.pct_change(periods=21, fill_method=None)
        mom_3m = close_px.pct_change(periods=63, fill_method=None)
        mom_6m = close_px.pct_change(periods=126, fill_method=None)
        
        # 4. Mean Reversion Factor (Short term)
        reversal_1w = -close_px.pct_change(periods=5, fill_method=None)
        
        # 4.5. Advanced Factors
        # Volume Shock: Volume today / 20-day MA of Volume
        vol_ma_20 = volume_px.rolling(window=20).mean()
        volume_shock = volume_px / vol_ma_20
        
        # Intraday Volatility Proxy (Normalized High-Low Range)
        intraday_vol = (high_px - low_px) / close_px
        
        # Restack everything
        factors = pd.DataFrame(index=df.index)
        factors['target'] = forward_returns.stack()
        factors['vol_20d'] = vol_20d.stack()
        factors['mom_1m'] = mom_1m.stack()
        factors['mom_3m'] = mom_3m.stack()
        factors['mom_6m'] = mom_6m.stack()
        factors['reversal_1w'] = reversal_1w.stack()
        factors['volume_shock'] = volume_shock.stack()
        factors['intraday_vol'] = intraday_vol.stack()
        
        # Drop NaN rows generated by rolling windows and target shifting
        factors = factors.dropna()
        
        # 5. Cross-Sectional Normalization (Rank)
        # Avoid outliers and make data stationary across time
        feature_cols = ['vol_20d', 'mom_1m', 'mom_3m', 'mom_6m', 'reversal_1w', 'volume_shock', 'intraday_vol']
        
        for col in feature_cols:
            # Rank across tickers for each date, then normalize to [-1, 1]
            # This is critical to remove market bias and stationary issues
            factors[col] = factors.groupby(level='Date')[col].transform(
                lambda x: (x.rank() - 1) / (len(x) - 1) * 2 - 1 if len(x) > 1 else 0
            )
            
        return factors, feature_cols
